language: java

dist: precise

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
  - "$HOME/.m2"

install:
  - mvn dependency:go-offline
  
script:
  - mvn clean verify
